language: node_js
node_js:
  - "8.9.1"

install:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install
  - bower install

script:
  - grunt

cache:
  directories:
    - "node_modules"
    - "bower_components"