language: node_js

install:
  - npm install
  - bower install

before_script:
  - npm install -g bower
  - npm install -g grunt-cli

script:
  - grunt

cache:
  directories:
    - "node_modules"
    - "bower_components"